import Link from "next/link";
import { InformationPage } from "@/components/information-page";

export const metadata = { title: "Leiðbeiningar og aðstoð | Mín fjármál" };

export default function HelpPage() {
  const supportEmail = process.env.SUPPORT_EMAIL;
  return <InformationPage title="Leiðbeiningar og aðstoð" description="Frá fyrstu færslu að skýrari yfirsýn. Hér finnurðu leiðbeiningar um skráningu og yfirsýn yfir fjármálin þín.">
    <section data-scroll-reveal=""><h2>Fyrsti mánuðurinn</h2><ol><li><Link href="/transactions#new-transaction">Skráðu tekjur og útgjöld</Link> eða flyttu inn útgjaldaskrá úr bankanum.</li><li>Yfirfarðu dagsetningar, upphæðir og flokka. Yfirlitið byggir á því sem hefur verið skráð.</li><li><Link href="/bills">Bættu við reikningum</Link> og tengdu greiðslur við færslur þegar við á.</li><li><Link href="/savings-goals">Settu sparnaðarmarkmið</Link> og dagsetningu til að sjá mánaðarlegt framlag.</li></ol><p>Upphæðir eru í íslenskum krónum (ISK). Engin sjálfvirk bankatenging eða gjaldeyrisumbreyting er í boði.</p></section>
    <section id="import" data-scroll-reveal=""><h2>Flytja inn útgjöld</h2><p>Innflutningur tekur við CSV og studdum Excel-útflutningi með dagsetningu, lýsingu og upphæð. Neikvæðar upphæðir eru túlkaðar sem útgjöld. Tekjur og jákvæðar færslur eru ekki fluttar inn í þessum innflutningi; skráðu tekjur sérstaklega.</p><ol><li>Veldu útflutningsskrá undir <Link href="/transactions#import-transactions">Flytja inn skrá</Link>.</li><li>Staðfestu hvaða dálkar innihalda dagsetningu, lýsingu og upphæð.</li><li>Yfirfarðu allar tillögur. Leiðréttu flokka og athugaðu línur sem eru ógildar eða kunna að vera tvíteknar.</li><li>Veldu þær færslur sem eiga að bætast við og staðfestu innflutninginn.</li></ol><p>Hægt er að muna dálkaval og reglur fyrir sambærilegar lýsingar á þessu tæki. Frumskráin er ekki vistuð með þessum stillingum. Niðurstaðan sýnir hversu margar færslur bættust við og hversu mörgum var sleppt.</p></section>
    <section data-scroll-reveal=""><h2>Tímabil og flokkun</h2><p>Í Færslum velurðu einn mánuð, sérstakt dagsetningabil eða öll tímabil. Samantektin fylgir völdum síum. Breyttu færslu beint í listanum eða veldu margar færslur og vistaðu sameiginlega flokkun.</p><p>Tekjuflokkar passa við tekjur, útgjaldaflokkar við útgjöld og sameiginlegir flokkar við hvort tveggja. Bættu við eigin flokkum í <Link href="/settings#category-settings">stillingum</Link>.</p></section>
    <section data-scroll-reveal=""><h2>Reikningar og greiðslur</h2><p>Ef greiðslan er þegar skráð eða flutt inn skaltu tengja þá útgjaldafærslu við reikninginn. Búðu aðeins til nýja útgjaldafærslu ef hún hefur ekki verið skráð. Við nýja skráningu velurðu raunverulega greiðsludagsetningu.</p><p>„Ógreitt“ merkir að greiðsla hefur ekki verið skráð hér. Síðan staðfestir ekki greiðslustöðu hjá bankanum. Aftenging greiðslu eyðir ekki útgjaldafærslunni.</p><p>Þú getur afritað valda reikninga frá fyrri mánuði. Greiðslur fylgja ekki með og reikningar úr sömu röð eru ekki afritaðir tvisvar í sama mánuð.</p></section>
    <section data-scroll-reveal=""><h2>Sparnaðaráætlun</h2><p>Mánaðarlegt framlag miðast við upphæðina sem vantar og mánuðina fram að markdegi, með núverandi mánuði. Áætlunin gerir ekki ráð fyrir ávöxtun. Framlagasagan og nýjasta framlag hvers flokks hjálpa þér að yfirfara skráninguna.</p></section>
    <section data-scroll-reveal=""><h2>Gögnin þín og aðgangur</h2><p>Í <Link href="/settings#data-settings">Gögn og aðstoð</Link> geturðu sótt færslur sem CSV, öll gögn aðgangsins á þjóninum sem JSON, eða skráð og afturkallað beiðni um eyðingu aðgangs. Stillingar sem eru aðeins vistaðar í vafranum fylgja ekki útflutningi. Eyðing þarf afgreiðslu stjórnanda og er ekki framkvæmd um leið og beiðnin er send.</p><p><Link href="/privacy">Lesa um meðferð gagna</Link>.</p></section>
    <section data-scroll-reveal=""><h2>Frekari aðstoð</h2>{supportEmail ? <p>Hafðu samband við <a href={`mailto:${supportEmail}`}>{supportEmail}</a>. Lýstu því hvaða aðgerð þú varst að framkvæma og hvaða skilaboð birtust.</p> : <p>Upplýsingar um hugbúnaðinn og verkefnishöfund eru á <a href="https://github.com/BjarturBlaer99/Heimafj-rm-l" target="_blank" rel="noreferrer">síðu verkefnisins</a>.</p>}<p>Ekki birta lykilorð, bankaskrár eða persónulegar fjármálaupplýsingar í opinberum villutilkynningum.</p></section>
  </InformationPage>;
}
