import Link from "next/link";
import { InformationPage } from "@/components/information-page";
import { privacyContact } from "@/lib/privacy-config";

export const metadata = { title: "Leiðbeiningar og aðstoð | Mín fjármál" };

export default function HelpPage() {
  const supportEmail = process.env.SUPPORT_EMAIL || privacyContact.email;
  return <InformationPage title="Leiðbeiningar og aðstoð" description="Hér geturðu lesið hvernig þú skráir færslur, heldur utan um reikninga og fylgist með sparnaðinum þínum.">
    <section data-scroll-reveal=""><h2>Svona byrjarðu</h2><ol><li><Link href="/transactions#new-transaction">Skráðu tekjur og útgjöld</Link> eða flyttu inn útgjöld úr skrá frá bankanum.</li><li>Farðu yfir dagsetningar, upphæðir og flokka. Yfirlitið miðast við það sem þú hefur skráð.</li><li><Link href="/bills">Bættu við reikningum</Link> og tengdu þá við skráðar greiðslur.</li><li><Link href="/savings-goals">Settu þér sparnaðarmarkmið</Link> og veldu hvenær þú vilt ná því. Þá sérðu hversu mikið þarf að leggja til hliðar á mánuði.</li></ol><p>Allar upphæðir eru í íslenskum krónum (ISK). Síðan tengist ekki bankanum þínum og umreiknar ekki upphæðir úr öðrum gjaldmiðlum.</p></section>
    <section id="import" data-scroll-reveal=""><h2>Flytja inn útgjöld</h2><p>Þú getur flutt inn CSV-skrár og studdar Excel-skrár með dagsetningu, lýsingu og upphæð. Neikvæðar upphæðir eru skráðar sem útgjöld. Jákvæðum upphæðum er sleppt, svo tekjur þarf að skrá sérstaklega.</p><ol><li>Veldu skrá úr bankanum undir <Link href="/transactions#import-transactions">Flytja inn skrá</Link>.</li><li>Veldu dálkana sem innihalda dagsetningu, lýsingu og upphæð.</li><li>Farðu yfir færslurnar og leiðréttu flokka eftir þörfum. Athugaðu sérstaklega færslur sem eru merktar ógildar eða hugsanlega tvíteknar.</li><li>Veldu þær færslur sem þú vilt bæta við og staðfestu innflutninginn.</li></ol><p>Þú getur látið vafrann muna dálkavalið og hvernig færslur með svipaðar lýsingar eru flokkaðar. Skráin sjálf er ekki vistuð með þessum stillingum. Að lokum sérðu hversu margar færslur bættust við og hversu mörgum var sleppt.</p></section>
    <section data-scroll-reveal=""><h2>Finna og flokka færslur</h2><p>Undir Færslur geturðu valið mánuð, ákveðið tímabil eða allar færslur. Samantektin sýnir tölur fyrir það sem þú hefur valið. Þú getur breytt færslu í listanum eða valið nokkrar færslur og flokkað þær saman.</p><p>Sumir flokkar eru eingöngu fyrir tekjur eða útgjöld. Aðra má nota fyrir hvort tveggja. Þú getur bætt við eigin flokkum í <Link href="/settings#category-settings">stillingum</Link>.</p></section>
    <section data-scroll-reveal=""><h2>Reikningar og greiðslur</h2><p>Ef greiðsla er þegar skráð skaltu tengja þá færslu við reikninginn. Þannig teljast útgjöldin ekki tvisvar. Ef greiðsluna vantar geturðu skráð hana um leið og þú merkir reikninginn greiddan. Veldu daginn sem þú greiddir.</p><p>„Ógreitt“ merkir að greiðslan hefur ekki verið skráð hér. Síðan kannar ekki hvort reikningurinn sé greiddur hjá bankanum. Ef þú aftengir greiðslu helst útgjaldafærslan í færslulistanum.</p><p>Þú getur afritað valda reikninga úr fyrri mánuði. Greiðslur fylgja ekki með. Reikningar úr sömu röð eru aðeins afritaðir einu sinni í hvern mánuð.</p></section>
    <section data-scroll-reveal=""><h2>Sparnaðaráætlun</h2><p>Mánaðarlegt framlag sýnir hversu mikið þarf að leggja til hliðar til að ná markmiðinu á þeim degi sem þú valdir. Upphæðinni sem vantar er skipt á mánuðina fram að þeim degi, að núverandi mánuði meðtöldum. Ekki er gert ráð fyrir ávöxtun. Í framlagasögunni geturðu séð hvað þú hefur lagt til hliðar og hvenær.</p></section>
    <section data-scroll-reveal=""><h2>Sækja gögn eða eyða aðgangi</h2><p>Undir <Link href="/settings#data-settings">Gögn og aðstoð</Link> geturðu sótt færslur sem CSV-skrá eða öll vistuð gögn aðgangsins sem JSON-skrá. Stillingar sem eru aðeins geymdar í vafranum fylgja ekki með.</p><p>Þar geturðu líka óskað eftir að aðganginum verði eytt eða afturkallað beiðni. Stjórnandi þarf að afgreiða eyðinguna; gögnunum er ekki eytt um leið og þú sendir beiðnina.</p><p><Link href="/privacy">Nánar um meðferð gagna</Link>.</p></section>
    <section data-scroll-reveal=""><h2>Vantar þig aðstoð?</h2>{supportEmail ? <p>Sendu póst á <a href={`mailto:${supportEmail}`}>{supportEmail}</a>. Segðu okkur hvað þú varst að gera og hvaða skilaboð birtust.</p> : <p>Þú finnur upplýsingar um síðuna og höfund hennar á <a href="https://github.com/BjarturBlaer99/Heimafj-rm-l" target="_blank" rel="noreferrer">síðu verkefnisins</a>.</p>}<p>Ekki birta lykilorð, bankaskrár eða persónulegar fjármálaupplýsingar þegar þú tilkynnir villu opinberlega.</p></section>
  </InformationPage>;
}
