import Link from "next/link";
import { InformationPage } from "@/components/information-page";
import { ExternalContentControls } from "@/components/external-content-controls";
import { getPrivacyDeployment, privacyContact } from "@/lib/privacy-config";

export const metadata = { title: "Persónuvernd | Mín fjármál" };
export const dynamic = "force-dynamic";

export default function PrivacyPage() {
  const deployment = getPrivacyDeployment();
  return <InformationPage title="Persónuvernd" description="Fjármálin þín eru persónuleg. Hér kemur fram hvaða upplýsingar síðan notar, hvers vegna og hvernig þú getur haft stjórn á þeim.">
    {!deployment.registrationOpen ? <aside className="rounded-xl border border-line/20 bg-surface p-5" aria-label="Staða nýskráningar"><p className="!mb-0">Nýskráning er ekki opin í þessari útgáfu. Verið er að ganga frá forsendum fyrir almennri notkun, þar á meðal varðveislu og hýsingu gagna. Þú getur <Link href="/demo">skoðað prufuútgáfuna</Link> með tilbúnum gögnum.</p></aside> : null}

    <section data-scroll-reveal=""><h2>Hver ber ábyrgð?</h2><p>{privacyContact.controller} rekur Mín fjármál og er ábyrgðaraðili að vinnslu persónuupplýsinga á síðunni. Þú getur haft samband vegna persónuverndar, aðstoðar eða beiðna um gögn á <a className="break-all" href={`mailto:${privacyContact.email}`}>{privacyContact.email}</a>.</p><p>Um vinnsluna gilda íslensk lög nr. 90/2018 um persónuvernd og vinnslu persónuupplýsinga og almenna persónuverndarreglugerðin (GDPR).</p></section>

    <section data-scroll-reveal=""><h2>Hvaða upplýsingar eru notaðar?</h2><ul className="list-disc pl-5"><li><strong>Aðgangurinn þinn:</strong> netfang, nafnið sem þú velur, upplýsingar sem þarf við innskráningu og staðfestingu aðgangs og stillingar þínar. Þú mátt nota gælunafn.</li><li><strong>Fjármálin sem þú skráir:</strong> upphæðir, dagsetningar, færslulýsingar, flokkar, áætlanir, reikningar, greiðslur, sparnaður og markmið. Þessar upplýsingar koma frá þér, annaðhvort með skráningu eða innflutningi.</li><li><strong>Samskipti og beiðnir:</strong> það sem þú sendir í aðstoðarbeiðni, beiðnir um eyðingu og upplýsingar sem þarf til að afgreiða þær.</li><li><strong>Rekstur og öryggi:</strong> þjónustuveitendur geta unnið með IP-tölu, tímasetningu tenginga, upplýsingar um vafra og villur þegar þeir hýsa vefinn og verja innskráningu.</li></ul><p>Síðan tengist ekki bankanum þínum. Ekki skrá bankalykilorð, kortanúmer, kennitölur eða viðkvæmar upplýsingar um þig eða aðra í færslulýsingar. Lýsing úr bankaskrá getur til dæmis sagt til um heilsu eða félagsaðild; þú getur breytt henni eða fjarlægt hana áður en skrá er flutt inn.</p></section>

    <section data-scroll-reveal=""><h2>Hvers vegna og á hvaða grundvelli?</h2><p>Upplýsingar um aðgang, færslur og sparnað eru notaðar til að veita þjónustuna sem þú biður um: vista skráningar, reikna yfirlit og gera þér kleift að breyta og sækja gögnin. Grundvöllurinn er framkvæmd samnings um notkun þjónustunnar. Netfang og innskráningarupplýsingar eru nauðsynleg fyrir aðgang; þú velur hvaða fjármálagögn þú skráir.</p><p>Nauðsynleg vinnsla vegna rekstraröryggis og varna gegn misnotkun byggist á lögmætum hagsmunum af því að verja þjónustuna og gögn notenda. Vinnsla til að svara réttindabeiðnum byggist á lagaskyldu.</p><p>Valfrjálst efni frá TradingView hleðst aðeins ef þú velur það. Sú tenging byggist á samþykki sem þú getur afturkallað. Notkun aðgangsins er ekki háð því vali.</p><p>Gögnin eru ekki seld eða notuð til markaðssetningar. Útreikningar og yfirlit hjálpa þér að skoða það sem þú hefur skráð; síðan tekur ekki sjálfvirkar ákvarðanir um lánshæfi, lánveitingar eða önnur réttindi þín.</p></section>

    <section data-scroll-reveal=""><h2>Þegar þú flytur inn skrá</h2><p>Skráin er fyrst lesin í vafranum. Færslurnar sem eru lesnar úr henni, þar á meðal upphæðir, dagsetningar og lýsingar, eru sendar til vefþjónsins til að athuga hvort þær séu þegar skráðar. Sú athugun getur því farið fram áður en þú staðfestir innflutning.</p><p>Aðeins færslurnar sem þú velur eru vistaðar í færslulistann þegar þú staðfestir. Upprunalega bankaskráin er ekki vistuð sem skrá hjá þjónustunni. Ef þú lætur vafrann muna flokkunarreglur geta þær innihaldið texta úr lýsingum. Þú getur hreinsað reglurnar í innflutningshlutanum.</p></section>

    <section data-scroll-reveal=""><h2>Hverjir fá aðgang að gögnunum?</h2><p>Supabase sér um gagnagrunn og innskráningu. Vercel hýsir vefinn og vinnur með gögn þegar síður og aðgerðir eru afgreiddar. Aðgangsstýring er notuð til að aðgreina gögn notenda. Rekstraraðili og heimilaðir starfsmenn þjónustuveitenda geta þurft tæknilegan aðgang vegna rekstrar, aðstoðar eða öryggis.</p><p>Þegar þú sendir tölvupóst er einnig unnið með erindið hjá tölvupóstþjónustunni. Ekki senda bankaskrár eða lykilorð með almennum tölvupósti. Ef þörf er á gögnum til að leysa erindi er samið um örugga afhendingu.</p><h3>Vistunarstaður</h3><p>{deployment.dataLocation ?? "Staðfestar upplýsingar um vistunarstað gagna verða birtar hér áður en nýskráning opnar."}</p><h3>Flutningur út fyrir EES</h3><p>{deployment.transferSafeguards ?? "Verið er að staðfesta hvort þjónustuveitendur eða undirvinnsluaðilar vinni með gögn utan EES og hvaða verndarráðstafanir eigi við. Þær upplýsingar verða birtar áður en nýskráning opnar."}</p><p>Þú getur óskað eftir upplýsingum um vinnsluaðila og afriti af viðeigandi verndarráðstöfunum með því að hafa samband við ábyrgðaraðila.</p></section>

    <section id="browser-data" data-scroll-reveal=""><h2>Vafrakökur og stillingar á tækinu</h2><p>Nauðsynlegar vafrakökur halda utan um innskráninguna. Vafrinn getur líka munað útlitsval, stöðu uppsetningar og innflutningsstillingar sem þú velur að vista. Innflutningsstillingar eru aðgreindar eftir aðgangi. Þessar stillingar eru geymdar á tækinu þar til þær eru hreinsaðar; þær flytjast ekki sjálfkrafa milli tækja.</p><p>Enginn auglýsinga- eða heimsóknamælingakóði er settur inn af Mínum fjármálum. TradingView er valfrjáls utanaðkomandi þjónusta. Ef þú virkjar gröfin fær TradingView meðal annars IP-töluna þína og upplýsingar sem fylgja tengingu vafrans. Fjármálafærslurnar þínar eru ekki sendar með gröfunum. Nánar er fjallað um vinnslu TradingView í <a href="https://www.tradingview.com/privacy-policy/" target="_blank" rel="noreferrer">persónuverndarstefnu þeirra</a>.</p><p>Valið um gröfin er geymt á þessu tæki í allt að 180 daga. Þú getur breytt því hér eða í stillingum. Afturköllun stöðvar frekari hleðslu hér en hefur ekki áhrif á lögmæti fyrri vinnslu og eyðir ekki sjálfkrafa upplýsingum sem TradingView hefur þegar fengið.</p><ExternalContentControls /></section>

    <section data-scroll-reveal=""><h2>Hversu lengi eru gögn geymd?</h2><p>Fjármálagögn og aðgangsstillingar eru geymd meðan þú heldur aðganginum og þar til þú eyðir viðkomandi skráningum eða beiðni um eyðingu aðgangs er afgreidd. Við eyðingu aðgangs eru tengd gögn fjarlægð úr virka gagnagrunninum. Aðgangar eyðast ekki sjálfkrafa vegna óvirkni í þessari útgáfu.</p><h3>Öryggisafrit</h3><p>{deployment.backupRetention ?? "Varðveislutími öryggisafrita er enn til staðfestingar. Eyðing úr virka kerfinu felur ekki í sér tafarlausa eyðingu úr afritum."}</p><h3>Rekstrar- og öryggisskrár</h3><p>{deployment.logRetention ?? "Varðveislutími rekstrar- og öryggisskráa verður birtur hér þegar stillingar þjónustuveitenda hafa verið staðfestar."}</p><h3>Aðstoð og réttindabeiðnir</h3><p>{deployment.supportRetention ?? "Ganga þarf frá varðveislutíma erinda og gagna um afgreiðslu þeirra áður en nýskráning opnar."}</p></section>

    <section data-scroll-reveal=""><h2>Réttindin þín</h2><p>Þú getur óskað eftir aðgangi að persónuupplýsingum þínum, afriti, leiðréttingu og eyðingu. Þú getur líka átt rétt á að takmarka vinnslu, andmæla vinnslu sem byggist á lögmætum hagsmunum og fá gögn á tölvulesanlegu sniði til að flytja annað. Réttindin eiga við samkvæmt skilyrðum persónuverndarlaga.</p><p>Í <Link href="/settings#data-settings">gagnastillingum</Link> geturðu sótt færslur sem CSV eða vistuð gögn aðgangsins sem JSON. Stillingar sem eru eingöngu í vafranum fylgja ekki með því afriti. Þú getur leiðrétt skráningar á viðkomandi síðum og óskað eftir eyðingu aðgangs í stillingum.</p><p>Eyðingarbeiðni er skráð með aðganginum og rekstraraðili þarf að afgreiða hana. Hún eyðir ekki gögnunum samstundis. Þú getur afturkallað beiðnina þar til eyðing fer fram. Aðrar réttindabeiðnir má senda á <a className="break-all" href={`mailto:${privacyContact.email}`}>{privacyContact.email}</a>.</p><p>Beiðnum er svarað án ótilhlýðilegrar tafar og að jafnaði innan eins mánaðar. Ef heimil framlenging er nauðsynleg vegna umfangs eða fjölda beiðna færðu upplýsingar um ástæðuna innan þess mánaðar; framlenging getur verið allt að tveir mánuðir til viðbótar. Staðfesta getur þurft hver sendir beiðni til að verja gögnin. Ekki senda skilríki nema sérstaklega hafi verið óskað eftir nauðsynlegum upplýsingum og örugg leið ákveðin.</p><p>Ef þú telur að farið sé rangt með gögnin þín geturðu <a href="https://island.is/s/personuvernd">leitað til Persónuverndar</a>, óháð því hvort þú hefur fyrst haft samband við okkur.</p></section>

    <section data-scroll-reveal=""><h2>Breytingar á stefnunni</h2><p>Stefnan er uppfærð þegar meðferð gagna breytist. Ef breyting hefur veruleg áhrif á notendur er þeim tilkynnt um hana áður en hún tekur gildi. Nýs samþykkis er óskað ef það er nauðsynlegt vegna breyttrar valfrjálsrar vinnslu.</p><p>Síðast uppfært 24. september 2026.</p></section>
  </InformationPage>;
}
